import { MigrationDescription } from '../../orm/migration/migration-description';

export const UserPoolRoleMigration: MigrationDescription = {
  id: 'user-pool-role',
  after: 'user-token',
  steps: [
    { kind: 'add_table', table: 'UserPoolRole' },
    {
      kind: 'add_table_field',
      table: 'UserPoolRole',
      fieldName: 'name',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserPoolRole',
      fieldName: 'description',
      type: 'string',
      required: false,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserPoolRole',
      fieldName: 'userPoolId',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    { kind: 'add_table_primary_key', table: 'UserPoolRole', fieldNames: ['name'] },
    { kind: 'add_table', table: 'UserPoolUser' },
    {
      kind: 'add_table_field',
      table: 'UserPoolUser',
      fieldName: 'userUsername',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserPoolUser',
      fieldName: 'userPoolId',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    { kind: 'add_table_primary_key', table: 'UserPoolUser', fieldNames: ['userPoolId', 'userUsername'] },
    {
      kind: 'add_table_field',
      fieldName: 'userPoolId',
      type: 'string',
      required: true,
      defaultValue: undefined,
      table: 'UserRefreshToken',
    },
    {
      kind: 'add_table_foreign_key',
      table: 'UserRefreshToken',
      name: 'userPool',
      fieldNames: ['userPoolId'],
      foreignFieldNames: ['id'],
      foreignTable: 'UserPool',
      required: true,
    },
    { kind: 'drop_table_foreign_key', table: 'UserRole', name: 'role' },
    { kind: 'drop_table', table: 'Role' },
    {
      kind: 'add_table_foreign_key',
      table: 'UserPoolRole',
      name: 'userPool',
      fieldNames: ['userPoolId'],
      foreignFieldNames: ['id'],
      foreignTable: 'UserPool',
      required: true,
    },
    {
      kind: 'add_table_foreign_key',
      table: 'UserPoolUser',
      name: 'user',
      fieldNames: ['userUsername'],
      foreignFieldNames: ['username'],
      foreignTable: 'User',
      required: true,
    },
    {
      kind: 'add_table_foreign_key',
      table: 'UserPoolUser',
      name: 'userPool',
      fieldNames: ['userPoolId'],
      foreignFieldNames: ['id'],
      foreignTable: 'UserPool',
      required: true,
    },
  ],
};
