import { MigrationDescription } from '../../orm/migration';

export const UserTokenMigration: MigrationDescription = {
  id: 'user-token',
  after: 'fifth',
  steps: [
    { kind: 'add_table', table: 'UserToken' },
    {
      kind: 'add_table_field',
      table: 'UserToken',
      fieldName: 'id',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserToken',
      fieldName: 'userUsername',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserToken',
      fieldName: 'name',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserToken',
      fieldName: 'token',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserToken',
      fieldName: 'expiresAt',
      type: 'date',
      required: false,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserToken',
      fieldName: 'createdAt',
      type: 'date',
      required: true,
      defaultValue: undefined,
    },
    { kind: 'add_table_primary_key', table: 'UserToken', fieldNames: ['token'] },
    {
      kind: 'add_table_foreign_key',
      table: 'UserToken',
      name: 'user',
      fieldNames: ['userUsername'],
      foreignFieldNames: ['username'],
      foreignTable: 'User',
      required: true,
    },
  ],
};
