import { AlterTableAddColumnFormatter } from '@daita/relational';
import { Formatter } from '@daita/relational';
import { CreateTableFormatter } from '@daita/relational';
import { DropTableFormatter } from '@daita/relational';
import { NowFormatter } from '../sql/function/date/now-formatter';
import { SqliteTableFormatter } from './sqlite-table-formatter';
import { ConcatPipeFormatter } from '@daita/relational';
import { ansiFormatter } from '@daita/relational';
import { LeastFormatter } from '@daita/relational';
import { GreatestFormatter } from '@daita/relational';

export const sqliteFormatter = new Formatter();
sqliteFormatter.extend(ansiFormatter);
sqliteFormatter.add(new NowFormatter());
sqliteFormatter.add(new DropTableFormatter());
sqliteFormatter.add(new CreateTableFormatter());
sqliteFormatter.add(new AlterTableAddColumnFormatter());
sqliteFormatter.add(new SqliteTableFormatter());
sqliteFormatter.add(new ConcatPipeFormatter());
sqliteFormatter.add(new LeastFormatter());
sqliteFormatter.add(new GreatestFormatter());
