---
kind: pipeline
type: docker
name: install

platform:
  os: linux
  arch: amd64

steps:
- name: install:@daita/eslint-config
  image: node:12
  commands:
  - cd packages/eslint-config
  - npm install
  - npm run build

- name: install:@daita/common
  image: node:12
  commands:
  - cd packages/common
  - npm install
  - npm run build
  depends_on:
  - install:@daita/eslint-config

- name: install:@daita/relational
  image: node:12
  commands:
  - cd packages/relational
  - npm install
  - npm run build
  depends_on:
  - install:@daita/common
  - install:@daita/eslint-config

- name: install:@daita/document
  image: node:12
  commands:
  - cd packages/document
  - npm install
  - npm run build
  depends_on:
  - install:@daita/common
  - install:@daita/eslint-config

- name: install:@daita/orm
  image: node:12
  commands:
  - cd packages/orm
  - npm install
  - npm run build
  depends_on:
  - install:@daita/common
  - install:@daita/relational
  - install:@daita/eslint-config

- name: install:@daita/odm
  image: node:12
  commands:
  - cd packages/odm
  - npm install
  - npm run build
  depends_on:
  - install:@daita/common
  - install:@daita/document
  - install:@daita/eslint-config

- name: install:@daita/mongodb
  image: node:12
  commands:
  - cd packages/adapters/mongodb
  - npm install
  - npm run build
  depends_on:
  - install:@daita/common
  - install:@daita/document

- name: install:@daita/pg
  image: node:12
  commands:
  - cd packages/adapters/pg
  - npm install
  - npm run build
  depends_on:
  - install:@daita/common
  - install:@daita/relational

- name: install:@daita/http-server
  image: node:12
  commands:
  - cd packages/http-server
  - npm install
  - npm run build
  depends_on:
  - install:@daita/common
  - install:@daita/relational

- name: install:@daita/http
  image: node:12
  commands:
  - cd packages/adapters/http
  - npm install
  - npm run build
  depends_on:
  - install:@daita/common
  - install:@daita/relational
  - install:@daita/http-server
  - install:@daita/pg

- name: install:@daita/websocket
  image: node:12
  commands:
  - cd packages/adapters/websocket
  - npm install
  - npm run build
  depends_on:
  - install:@daita/common
  - install:@daita/relational
  - install:@daita/http-server
  - install:@daita/pg

- name: install:@daita/cli
  image: node:12
  commands:
  - cd packages/cli
  - npm install
  - npm run build
  depends_on:
  - install:@daita/common
  - install:@daita/http-server
  - install:@daita/relational
  - install:@daita/mongodb
  - install:@daita/pg

---
kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build:@daita/eslint-config
  image: node:12
  commands:
  - cd packages/eslint-config
  - npm install
  - npm run build

- name: build:@daita/common
  image: node:12
  commands:
  - cd packages/common
  - npm install
  - npm run build
  depends_on:
  - build:@daita/eslint-config

- name: build:@daita/relational
  image: node:12
  commands:
  - cd packages/relational
  - npm install
  - npm run build
  depends_on:
  - build:@daita/common
  - build:@daita/eslint-config

- name: build:@daita/document
  image: node:12
  commands:
  - cd packages/document
  - npm install
  - npm run build
  depends_on:
  - build:@daita/common
  - build:@daita/eslint-config

- name: build:@daita/orm
  image: node:12
  commands:
  - cd packages/orm
  - npm install
  - npm run build
  depends_on:
  - build:@daita/common
  - build:@daita/relational
  - build:@daita/eslint-config

- name: build:@daita/odm
  image: node:12
  commands:
  - cd packages/odm
  - npm install
  - npm run build
  depends_on:
  - build:@daita/common
  - build:@daita/document
  - build:@daita/eslint-config

- name: build:@daita/mongodb
  image: node:12
  commands:
  - cd packages/adapters/mongodb
  - npm install
  - npm run build
  depends_on:
  - build:@daita/common
  - build:@daita/document

- name: build:@daita/pg
  image: node:12
  commands:
  - cd packages/adapters/pg
  - npm install
  - npm run build
  depends_on:
  - build:@daita/common
  - build:@daita/relational

- name: build:@daita/http-server
  image: node:12
  commands:
  - cd packages/http-server
  - npm install
  - npm run build
  depends_on:
  - build:@daita/common
  - build:@daita/relational

- name: build:@daita/http
  image: node:12
  commands:
  - cd packages/adapters/http
  - npm install
  - npm run build
  depends_on:
  - build:@daita/common
  - build:@daita/relational
  - build:@daita/http-server
  - build:@daita/pg

- name: build:@daita/websocket
  image: node:12
  commands:
  - cd packages/adapters/websocket
  - npm install
  - npm run build
  depends_on:
  - build:@daita/common
  - build:@daita/relational
  - build:@daita/http-server
  - build:@daita/pg

- name: build:@daita/cli
  image: node:12
  commands:
  - cd packages/cli
  - npm install
  - npm run build
  depends_on:
  - build:@daita/common
  - build:@daita/http-server
  - build:@daita/relational
  - build:@daita/mongodb
  - build:@daita/pg

depends_on:
- install

...
