name: default

kind: pipeline
type: docker

steps:
- name: install
  image: node:12
  commands:
  - yarn install

- name: build:core
  image: node:12
  depends_on: [install]
  commands:
    - cd packages/core
    - yarn build

- name: build:website
  image: node:12
  depends_on: [install]
  commands:
    - cd packages/website
    - yarn build

- name: build:tslint
  image: node:12
  depends_on: [install]
  commands:
    - cd packages/tslint
    - yarn build

- name: build:web-client
  image: node:12
  depends_on: [install, build:core]
  commands:
    - cd packages/web-client
    - yarn build

- name: build:web
  image: node:12
  depends_on: [install, build:core]
  commands:
    - cd packages/web
    - yarn build

- name: build:cli
  image: node:12
  depends_on: [install, build:core, build:web]
  commands:
    - cd packages/cli
    - yarn build

- name: build:example:node
  image: node:12
  depends_on: [install, build:core, build:cli]
  commands:
    - cd packages/examples/node-example
    - yarn build

- name: build:example:angular
  image: node:12
  depends_on: [install, build:core, build:cli, build:web-client]
  commands:
    - cd packages/examples/angular-todo
    - yarn build

- name: test
  image: node:12
  depends_on: [install, build:core, build:cli, build:web, build:web-client]
  environment:
    POSTGRES_URI: postgres://postgres:postgres@postgres
  commands:
    - yarn coverage

- name: codacy
  image: node:12
  depends_on: [test]
  commands:
    - npm install codacy-coverage
    - cat coverage/lcov.info | codacy-coverage
  environment:
    CODACY_PROJECT_TOKEN:
      from_secret: codacy_api_token

services:
  - name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

trigger:
  branch:
    exclude:
      - gh-pages

---

name: pages

kind: pipeline
type: docker

steps:
- name: build
  image: node:12
  commands:
  - cd packages/website
  - npm install
  - npm run build

- name: publish
  image: plugins/gh-pages
  settings:
    pages_directory: packages/website/public/
  commands: []

trigger:
  event:
    - push
  branch:
    - master