---
kind: pipeline
type: docker
name: daita

platform:
  os: linux
  arch: amd64

steps:
- name: "@daita/eslint-config:install"
  image: node:12
  commands:
  - cd packages/eslint-config
  - npm install

- name: "@daita/docs:install"
  image: node:12
  commands:
  - cd packages/docs
  - npm install

- name: "@daita/common:install"
  image: node:12
  commands:
  - cd packages/common
  - npm install
  depends_on:
  - "@daita/eslint-config:install"

- name: "@daita/create:install"
  image: node:12
  commands:
  - cd packages/create
  - npm install
  depends_on:
  - "@daita/eslint-config:install"

- name: "@daita/relational:install"
  image: node:12
  commands:
  - cd packages/relational
  - npm install
  depends_on:
  - "@daita/common:install"
  - "@daita/eslint-config:install"

- name: "@daita/pg-adapter:install"
  image: node:12
  commands:
  - cd packages/pg-adapter
  - npm install
  depends_on:
  - "@daita/common:install"
  - "@daita/relational:install"

- name: "@daita/sqlite-adapter:install"
  image: node:12
  commands:
  - cd packages/sqlite-adapter
  - npm install
  depends_on:
  - "@daita/common:install"
  - "@daita/relational:install"

- name: "@daita/http-client-common:install"
  image: node:12
  commands:
  - cd packages/http/http-client-common
  - npm install
  depends_on:
  - "@daita/common:install"

- name: "@daita/http-server-common:install"
  image: node:12
  commands:
  - cd packages/http/http-server-common
  - npm install
  depends_on:
  - "@daita/common:install"
  - "@daita/relational:install"

- name: "@daita/http-server:install"
  image: node:12
  commands:
  - cd packages/http/http-server
  - npm install
  depends_on:
  - "@daita/common:install"
  - "@daita/http-server-common:install"
  - "@daita/relational:install"
  - "@daita/pg-adapter:install"

- name: "@daita/http-adapter:install"
  image: node:12
  commands:
  - cd packages/http/http-adapter
  - npm install
  depends_on:
  - "@daita/common:install"
  - "@daita/http-client-common:install"
  - "@daita/relational:install"
  - "@daita/http-server:install"

- name: "@daita/orm:install"
  image: node:12
  commands:
  - cd packages/orm
  - npm install
  depends_on:
  - "@daita/common:install"
  - "@daita/relational:install"
  - "@daita/eslint-config:install"

- name: "@daita/cli:install"
  image: node:12
  commands:
  - cd packages/cli
  - npm install
  depends_on:
  - "@daita/common:install"
  - "@daita/http-server:install"
  - "@daita/orm:install"
  - "@daita/relational:install"
  - "@daita/http-adapter:install"
  - "@daita/pg-adapter:install"

- name: "@daita/eslint-config:build"
  image: node:12
  commands:
  - cd packages/eslint-config
  - npm run build

- name: "@daita/docs:build"
  image: node:12
  commands:
  - cd packages/docs
  - npm run build

- name: "@daita/common:build"
  image: node:12
  commands:
  - cd packages/common
  - npm run build
  depends_on:
  - "@daita/eslint-config:build"

- name: "@daita/create:build"
  image: node:12
  commands:
  - cd packages/create
  - npm run build
  depends_on:
  - "@daita/eslint-config:build"

- name: "@daita/relational:build"
  image: node:12
  commands:
  - cd packages/relational
  - npm run build
  depends_on:
  - "@daita/common:build"
  - "@daita/eslint-config:build"

- name: "@daita/pg-adapter:build"
  image: node:12
  commands:
  - cd packages/pg-adapter
  - npm run build
  depends_on:
  - "@daita/common:build"
  - "@daita/relational:build"

- name: "@daita/sqlite-adapter:build"
  image: node:12
  commands:
  - cd packages/sqlite-adapter
  - npm run build
  depends_on:
  - "@daita/common:build"
  - "@daita/relational:build"

- name: "@daita/http-client-common:build"
  image: node:12
  commands:
  - cd packages/http/http-client-common
  - npm run build
  depends_on:
  - "@daita/common:build"

- name: "@daita/http-server-common:build"
  image: node:12
  commands:
  - cd packages/http/http-server-common
  - npm run build
  depends_on:
  - "@daita/common:build"
  - "@daita/relational:build"

- name: "@daita/http-server:build"
  image: node:12
  commands:
  - cd packages/http/http-server
  - npm run build
  depends_on:
  - "@daita/common:build"
  - "@daita/http-server-common:build"
  - "@daita/relational:build"
  - "@daita/pg-adapter:build"

- name: "@daita/http-adapter:build"
  image: node:12
  commands:
  - cd packages/http/http-adapter
  - npm run build
  depends_on:
  - "@daita/common:build"
  - "@daita/http-client-common:build"
  - "@daita/relational:build"
  - "@daita/http-server:build"

- name: "@daita/orm:build"
  image: node:12
  commands:
  - cd packages/orm
  - npm run build
  depends_on:
  - "@daita/common:build"
  - "@daita/relational:build"
  - "@daita/eslint-config:build"

- name: "@daita/cli:build"
  image: node:12
  commands:
  - cd packages/cli
  - npm run build
  depends_on:
  - "@daita/common:build"
  - "@daita/http-server:build"
  - "@daita/orm:build"
  - "@daita/relational:build"
  - "@daita/http-adapter:build"
  - "@daita/pg-adapter:build"

- name: publish
  image: plugins/gh-pages
  settings:
    pages_directory: packages/docs/build/
  depends_on:
  - "@daita/docs:build"

...
