---
kind: pipeline
type: docker
name: "@daita/eslint-config"

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:12
  commands:
  - cd packages/eslint-config
  - npm install

- name: build
  image: node:12
  commands:
  - cd packages/eslint-config
  - npm run build

---
kind: pipeline
type: docker
name: "@daita/common"

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:12
  commands:
  - cd packages/common
  - npm install

- name: build
  image: node:12
  commands:
  - cd packages/common
  - npm run build

depends_on:
- "@daita/eslint-config"

---
kind: pipeline
type: docker
name: "@daita/relational"

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:12
  commands:
  - cd packages/relational
  - npm install

- name: build
  image: node:12
  commands:
  - cd packages/relational
  - npm run build

depends_on:
- "@daita/common"
- "@daita/eslint-config"

---
kind: pipeline
type: docker
name: "@daita/document"

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:12
  commands:
  - cd packages/document
  - npm install

- name: build
  image: node:12
  commands:
  - cd packages/document
  - npm run build

depends_on:
- "@daita/common"
- "@daita/eslint-config"

---
kind: pipeline
type: docker
name: "@daita/orm"

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:12
  commands:
  - cd packages/orm
  - npm install

- name: build
  image: node:12
  commands:
  - cd packages/orm
  - npm run build

depends_on:
- "@daita/common"
- "@daita/relational"
- "@daita/eslint-config"

---
kind: pipeline
type: docker
name: "@daita/odm"

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:12
  commands:
  - cd packages/odm
  - npm install

- name: build
  image: node:12
  commands:
  - cd packages/odm
  - npm run build

depends_on:
- "@daita/common"
- "@daita/document"
- "@daita/eslint-config"

---
kind: pipeline
type: docker
name: "@daita/mongodb"

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:12
  commands:
  - cd packages/adapters/mongodb
  - npm install

- name: build
  image: node:12
  commands:
  - cd packages/adapters/mongodb
  - npm run build

depends_on:
- "@daita/common"
- "@daita/document"

---
kind: pipeline
type: docker
name: "@daita/pg"

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:12
  commands:
  - cd packages/adapters/pg
  - npm install

- name: build
  image: node:12
  commands:
  - cd packages/adapters/pg
  - npm run build

depends_on:
- "@daita/common"
- "@daita/relational"

---
kind: pipeline
type: docker
name: "@daita/http-server"

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:12
  commands:
  - cd packages/http-server
  - npm install

- name: build
  image: node:12
  commands:
  - cd packages/http-server
  - npm run build

depends_on:
- "@daita/common"
- "@daita/relational"

---
kind: pipeline
type: docker
name: "@daita/http"

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:12
  commands:
  - cd packages/adapters/http
  - npm install

- name: build
  image: node:12
  commands:
  - cd packages/adapters/http
  - npm run build

depends_on:
- "@daita/common"
- "@daita/relational"
- "@daita/http-server"
- "@daita/pg"

---
kind: pipeline
type: docker
name: "@daita/websocket"

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:12
  commands:
  - cd packages/adapters/websocket
  - npm install

- name: build
  image: node:12
  commands:
  - cd packages/adapters/websocket
  - npm run build

depends_on:
- "@daita/common"
- "@daita/relational"
- "@daita/http-server"
- "@daita/pg"

---
kind: pipeline
type: docker
name: "@daita/cli"

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:12
  commands:
  - cd packages/cli
  - npm install

- name: build
  image: node:12
  commands:
  - cd packages/cli
  - npm run build

depends_on:
- "@daita/common"
- "@daita/http-server"
- "@daita/relational"
- "@daita/mongodb"
- "@daita/pg"

...
