name: default

kind: pipeline
type: docker

steps:
- name: build
  image: node:12
  commands:
  - yarn install
  - yarn lerna run build

trigger:
  branch:
    exclude:
      - gh-pages

---

name: pages

kind: pipeline
type: docker

steps:
- name: build
  image: node:12
  commands:
  - cd packages/website
  - npm install
  - npm run build

- name: publish
  image: plugins/gh-pages
  settings:
    pages_directory: packages/website/public/
  commands: []

trigger:
  branch:
    - master