---
kind: pipeline
type: docker
name: "@daita/eslint-config"

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:12
  commands:
  - cd packages/eslint-config
  - npm install

- name: build
  image: node:12
  commands:
  - cd packages/eslint-config
  - npm run build

---
kind: pipeline
type: docker
name: "@daita/docs"

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:12
  commands:
  - cd packages/docs
  - npm install

- name: build
  image: node:12
  commands:
  - cd packages/docs
  - npm run build

- name: publish
  image: plugins/gh-pages
  settings:
    pages_directory: packages/docs/build/

---
kind: pipeline
type: docker
name: "@daita/common"

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:12
  commands:
  - cd packages/common
  - npm install

- name: build
  image: node:12
  commands:
  - cd packages/common
  - npm run build

depends_on:
- "@daita/eslint-config"

---
kind: pipeline
type: docker
name: "@daita/create"

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:12
  commands:
  - cd packages/create
  - npm install

- name: build
  image: node:12
  commands:
  - cd packages/create
  - npm run build

depends_on:
- "@daita/eslint-config"

---
kind: pipeline
type: docker
name: "@daita/relational"

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:12
  commands:
  - cd packages/relational
  - npm install

- name: build
  image: node:12
  commands:
  - cd packages/relational
  - npm run build

depends_on:
- "@daita/common"
- "@daita/eslint-config"

---
kind: pipeline
type: docker
name: "@daita/pg-adapter"

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:12
  commands:
  - cd packages/pg-adapter
  - npm install

- name: build
  image: node:12
  commands:
  - cd packages/pg-adapter
  - npm run build

depends_on:
- "@daita/common"
- "@daita/relational"

---
kind: pipeline
type: docker
name: "@daita/sqlite-adapter"

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:12
  commands:
  - cd packages/sqlite-adapter
  - npm install

- name: build
  image: node:12
  commands:
  - cd packages/sqlite-adapter
  - npm run build

depends_on:
- "@daita/common"
- "@daita/relational"

---
kind: pipeline
type: docker
name: "@daita/http-client-common"

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:12
  commands:
  - cd packages/http/http-client-common
  - npm install

- name: build
  image: node:12
  commands:
  - cd packages/http/http-client-common
  - npm run build

depends_on:
- "@daita/common"

---
kind: pipeline
type: docker
name: "@daita/http-server-common"

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:12
  commands:
  - cd packages/http/http-server-common
  - npm install

- name: build
  image: node:12
  commands:
  - cd packages/http/http-server-common
  - npm run build

depends_on:
- "@daita/common"
- "@daita/relational"

---
kind: pipeline
type: docker
name: "@daita/http-server"

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:12
  commands:
  - cd packages/http/http-server
  - npm install

- name: build
  image: node:12
  commands:
  - cd packages/http/http-server
  - npm run build

depends_on:
- "@daita/common"
- "@daita/http-server-common"
- "@daita/relational"
- "@daita/pg-adapter"

---
kind: pipeline
type: docker
name: "@daita/http-adapter"

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:12
  commands:
  - cd packages/http/http-adapter
  - npm install

- name: build
  image: node:12
  commands:
  - cd packages/http/http-adapter
  - npm run build

depends_on:
- "@daita/common"
- "@daita/http-client-common"
- "@daita/relational"
- "@daita/http-server"

---
kind: pipeline
type: docker
name: "@daita/orm"

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:12
  commands:
  - cd packages/orm
  - npm install

- name: build
  image: node:12
  commands:
  - cd packages/orm
  - npm run build

depends_on:
- "@daita/common"
- "@daita/relational"
- "@daita/eslint-config"

---
kind: pipeline
type: docker
name: "@daita/cli"

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:12
  commands:
  - cd packages/cli
  - npm install

- name: build
  image: node:12
  commands:
  - cd packages/cli
  - npm run build

depends_on:
- "@daita/common"
- "@daita/http-server"
- "@daita/orm"
- "@daita/relational"
- "@daita/http-adapter"
- "@daita/pg-adapter"

...
