import { aliasTest } from './alias.test';
import { allTest } from './all.test';
import { RelationalTest } from '../../relational-test';
import { andTest } from './and.test';
import { ascTest } from './asc.test';
import { avgTest } from './avg.test';
import { betweenTest } from './between.test';
import { concatTest } from './concat.test';
import { countTest } from './count.test';
import { descTest } from './desc.test';
import { equalTest } from './equal.test';
import { existsTest } from './exists.test';
import { greaterEqualThanTest } from './greater-equal-than.test';
import { greaterThanTest } from './greater-than.test';
import { inTest } from './in.test';
import { isNullTest } from './is-null.test';
import { joinTest } from './join.test';
import { leftJoinTest } from './left-join.test';
import { likeTest } from './like.test';
import { maxTest } from './max.test';
import { minTest } from './min.test';
import { notBetweenTest } from './not-between.test';
import { notEqualTest } from './not-equal.test';
import { notInTest } from './not-in.test';
import { nowTest } from './now.test';
import { orTest } from './or.test';
import { subSelectTest } from './sub-select.test';
import { sumTest } from './sum.test';

export function selectFunctionTest(arg: RelationalTest) {
  aliasTest(arg);
  allTest(arg);
  andTest(arg);
  ascTest(arg);
  avgTest(arg);
  betweenTest(arg);
  concatTest(arg);
  countTest(arg);
  descTest(arg);
  equalTest(arg);
  existsTest(arg);
  greaterEqualThanTest(arg);
  greaterThanTest(arg);
  inTest(arg);
  isNullTest(arg);
  joinTest(arg);
  leftJoinTest(arg);
  likeTest(arg);
  maxTest(arg);
  minTest(arg);
  notBetweenTest(arg);
  notEqualTest(arg);
  notInTest(arg);
  nowTest(arg);
  orTest(arg);
  subSelectTest(arg);
  sumTest(arg);
}
