import { aliasTest } from './alias.spec';
import { allTest } from './all.spec';
import { RelationalTest } from '../../relational-test';
import { andTest } from './and.spec';
import { ascTest } from './asc.spec';
import { avgTest } from './avg.spec';
import { betweenTest } from './between.spec';
import { concatTest } from './concat.spec';
import { countTest } from './count.spec';
import { descTest } from './desc.spec';
import { equalTest } from './equal.spec';
import { existsTest } from './exists.spec';
import { greaterEqualThanTest } from './greater-equal-than.spec';
import { greaterThanTest } from './greater-than.spec';
import { inTest } from './in.spec';
import { isNullTest } from './is-null.spec';
import { joinTest } from './join.spec';
import { leftJoinTest } from './left-join.spec';
import { likeTest } from './like.spec';
import { maxTest } from './max.spec';
import { minTest } from './min.spec';
import { notBetweenTest } from './not-between.spec';
import { notEqualTest } from './not-equal.spec';
import { notInTest } from './not-in.spec';
import { nowTest } from './now.spec';
import { orTest } from './or.spec';
import { subSelectTest } from './sub-select.spec';
import { sumTest } from './sum.spec';

export function selectFunctionTest(arg: RelationalTest) {
  aliasTest(arg);
  allTest(arg);
  andTest(arg);
  ascTest(arg);
  avgTest(arg);
  betweenTest(arg);
  concatTest(arg);
  countTest(arg);
  descTest(arg);
  equalTest(arg);
  existsTest(arg);
  greaterEqualThanTest(arg);
  greaterThanTest(arg);
  inTest(arg);
  isNullTest(arg);
  joinTest(arg);
  leftJoinTest(arg);
  likeTest(arg);
  maxTest(arg);
  minTest(arg);
  notBetweenTest(arg);
  notEqualTest(arg);
  notInTest(arg);
  nowTest(arg);
  orTest(arg);
  subSelectTest(arg);
  sumTest(arg);
}
