import { Formatter } from './formatter';
import { AllFormatter } from '../sql/keyword/all/all-formatter';
import { UpdateFormatter } from '../sql/dml/update/update-formatter';
import { NotEqualFormatter } from '../sql/operands/comparison/not-equal/not-equal-formatter';
import { MaxFormatter } from '../sql/function/aggregation/max/max-formatter';
import { SelectFormatter } from '../sql/dml/select/select-formatter';
import { SubSelectFormatter } from '../sql/dml/select/subquery/sub-select-formatter';
import { ValueFormatter } from '../sql/operands/value-formatter';
import { SumFormatter } from '../sql/function/aggregation/sum/sum-formatter';
import { NotInFormatter } from '../sql/operands/comparison/not-in/not-in-formatter';
import { JoinFormatter } from '../sql/dml/select/join/join-formatter';
import { AvgFormatter } from '../sql/function/aggregation/avg/avg-formatter';
import { MinFormatter } from '../sql/function/aggregation/min/min-formatter';
import { IsNullFormatter } from '../sql/operands/comparison/is-null/is-null-formatter';
import { FieldFormatter } from '../sql/keyword/field/field-formatter';
import { BetweenFormatter } from '../sql/operands/comparison/between/between-formatter';
import { CountFormatter } from '../sql/function/aggregation/count/count-formatter';
import { OrderByFormatter } from '../sql/dml/select/order-by/order-by-formatter';
import { EqualFormatter } from '../sql/operands/comparison/equal/equal-formatter';
import { OrFormatter } from '../sql/keyword/or/or-formatter';
import { AndFormatter } from '../sql/keyword/and/and-formatter';
import { InFormatter } from '../sql/operands/comparison/in/in-formatter';
import { GreaterThanFormatter } from '../sql/operands/comparison/greater-than/greater-than-formatter';
import { GreaterEqualThanFormatter } from '../sql/operands/comparison/greater-equal-than/greater-equal-than-formatter';
import { LowerThanFormatter } from '../sql/operands/comparison/lower-than/lower-than-formatter';
import { LowerEqualThanFormatter } from '../sql/operands/comparison/lower-equal-than/lower-equal-than-formatter';
import { ExistsFormatter } from '../sql/dml/select/subquery/exists-formatter';
import { AliasFormatter } from '../sql/keyword/alias/alias-formatter';
import { NotBetweenFormatter } from '../sql/operands/comparison/not-between/not-between-formatter';
import { DeleteFormatter } from '../sql/dml/delete/delete-formatter';
import { LikeFormatter } from '../sql/operands/comparison/like/like-formatter';
import { InsertFormatter } from '../sql/dml/insert/insert-formatter';
import { AddFormatter } from '../sql/operands/arithmetic/add/add-formatter';
import { SubtractFormatter } from '../sql/operands/arithmetic/substract/subtract-formatter';
import { MultiplyFormatter } from '../sql/operands/arithmetic/multiply/multiply-formatter';
import { DivideFormatter } from '../sql/operands/arithmetic/divide/divide-formatter';
import { CoalesceFormatter } from '../sql/function/conditional/coalesce/coalesce-formatter';
import { CaseWhenFormatter } from '../sql/function/conditional/case-when/case-when-formatter';
import { IsNotNullFormatter } from '../sql/operands/comparison/is-not-null/is-not-null-formatter';
import { RoundFormatter } from '../sql/function/numeric/round/round-formatter';

export const ansiFormatter = new Formatter();

ansiFormatter.add(new AllFormatter());
ansiFormatter.add(new UpdateFormatter());
ansiFormatter.add(new NotEqualFormatter());
ansiFormatter.add(new MaxFormatter());
ansiFormatter.add(new SelectFormatter());
ansiFormatter.add(new SubSelectFormatter());
ansiFormatter.add(new ValueFormatter());
ansiFormatter.add(new CaseWhenFormatter());
ansiFormatter.add(new CoalesceFormatter());
ansiFormatter.add(new SumFormatter());
ansiFormatter.add(new AddFormatter());
ansiFormatter.add(new SubtractFormatter());
ansiFormatter.add(new MultiplyFormatter());
ansiFormatter.add(new DivideFormatter());
ansiFormatter.add(new NotInFormatter());
ansiFormatter.add(new JoinFormatter());
ansiFormatter.add(new AvgFormatter());
ansiFormatter.add(new MinFormatter());
ansiFormatter.add(new IsNullFormatter());
ansiFormatter.add(new IsNotNullFormatter());
ansiFormatter.add(new FieldFormatter());
ansiFormatter.add(new BetweenFormatter());
ansiFormatter.add(new CountFormatter());
ansiFormatter.add(new OrderByFormatter());
ansiFormatter.add(new EqualFormatter());
ansiFormatter.add(new OrFormatter());
ansiFormatter.add(new AndFormatter());
ansiFormatter.add(new InFormatter());
ansiFormatter.add(new GreaterThanFormatter());
ansiFormatter.add(new GreaterEqualThanFormatter());
ansiFormatter.add(new LowerThanFormatter());
ansiFormatter.add(new LowerEqualThanFormatter());
ansiFormatter.add(new ExistsFormatter());
ansiFormatter.add(new AliasFormatter());
ansiFormatter.add(new NotBetweenFormatter());
ansiFormatter.add(new DeleteFormatter());
ansiFormatter.add(new LikeFormatter());
ansiFormatter.add(new InsertFormatter());
ansiFormatter.add(new RoundFormatter());
