version: '3.5'
services:
  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=daita
    networks:
      - common
    #volumes:
      #- postgres-data:/var/lib/postgresql/data

  server:
    image: test-server
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/daita
    networks:
      - common
    ports:
      - 3000:3000

networks:
  common:
    name: common

volumes:
  postgres-data:
