import { MigrationDescription } from '../../orm/migration/migration-description';

export const InitMigration: MigrationDescription = {
  id: 'init',
  steps: [
    { kind: 'add_table', table: 'User' },
    {
      kind: 'add_table_field',
      table: 'User',
      fieldName: 'username',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'User',
      fieldName: 'email',
      type: 'string',
      required: false,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'User',
      fieldName: 'emailVerified',
      type: 'boolean',
      required: false,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'User',
      fieldName: 'phone',
      type: 'string',
      required: false,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'User',
      fieldName: 'phoneVerified',
      type: 'boolean',
      required: false,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'User',
      fieldName: 'password',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'User',
      fieldName: 'disabled',
      type: 'boolean',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'User',
      fieldName: 'userPoolId',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    { kind: 'add_table_primary_key', table: 'User', fieldNames: ['username'] },
    { kind: 'add_table', table: 'UserPool' },
    {
      kind: 'add_table_field',
      table: 'UserPool',
      fieldName: 'id',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserPool',
      fieldName: 'name',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserPool',
      fieldName: 'allowRegistration',
      type: 'boolean',
      required: false,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserPool',
      fieldName: 'algorithm',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserPool',
      fieldName: 'accessTokenExpiresIn',
      type: 'number',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserPool',
      fieldName: 'refreshRefreshExpiresIn',
      type: 'number',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserPool',
      fieldName: 'emailVerifyExpiresIn',
      type: 'number',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserPool',
      fieldName: 'passwordRegex',
      type: 'string',
      required: false,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserPool',
      fieldName: 'checkPasswordForBreach',
      type: 'boolean',
      required: false,
      defaultValue: undefined,
    },
    { kind: 'add_table_primary_key', table: 'UserPool', fieldNames: ['id'] },
    { kind: 'add_table', table: 'Role' },
    {
      kind: 'add_table_field',
      table: 'Role',
      fieldName: 'name',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'Role',
      fieldName: 'description',
      type: 'string',
      required: false,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'Role',
      fieldName: 'userPoolId',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    { kind: 'add_table_primary_key', table: 'Role', fieldNames: ['name', 'userPoolId'] },
    { kind: 'add_table', table: 'UserRole' },
    {
      kind: 'add_table_field',
      table: 'UserRole',
      fieldName: 'userUsername',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserRole',
      fieldName: 'roleName',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserRole',
      fieldName: 'roleUserPoolId',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    { kind: 'add_table_primary_key', table: 'UserRole', fieldNames: ['userUsername', 'roleName'] },
    { kind: 'add_table', table: 'UserReset' },
    {
      kind: 'add_table_field',
      table: 'UserReset',
      fieldName: 'userUsername',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserReset',
      fieldName: 'code',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserReset',
      fieldName: 'issuedAt',
      type: 'boolean',
      required: true,
      defaultValue: undefined,
    },
    { kind: 'add_table_primary_key', table: 'UserReset', fieldNames: ['code'] },
    { kind: 'add_table', table: 'UserEmailVerify' },
    {
      kind: 'add_table_field',
      table: 'UserEmailVerify',
      fieldName: 'userUsername',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserEmailVerify',
      fieldName: 'email',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserEmailVerify',
      fieldName: 'code',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserEmailVerify',
      fieldName: 'issuedAt',
      type: 'date',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserEmailVerify',
      fieldName: 'verifiedAt',
      type: 'date',
      required: false,
      defaultValue: undefined,
    },
    { kind: 'add_table_primary_key', table: 'UserEmailVerify', fieldNames: ['code'] },
    { kind: 'add_table', table: 'UserPoolCors' },
    {
      kind: 'add_table_field',
      table: 'UserPoolCors',
      fieldName: 'id',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserPoolCors',
      fieldName: 'userPoolId',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserPoolCors',
      fieldName: 'url',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    { kind: 'add_table_primary_key', table: 'UserPoolCors', fieldNames: ['id'] },
    { kind: 'add_table', table: 'UserRefreshToken' },
    {
      kind: 'add_table_field',
      table: 'UserRefreshToken',
      fieldName: 'token',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserRefreshToken',
      fieldName: 'userUsername',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserRefreshToken',
      fieldName: 'userPoolId',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserRefreshToken',
      fieldName: 'issuedAt',
      type: 'date',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserRefreshToken',
      fieldName: 'authorizedAt',
      type: 'date',
      required: true,
      defaultValue: undefined,
    },
    { kind: 'add_table_primary_key', table: 'UserRefreshToken', fieldNames: ['token'] },
    { kind: 'add_table', table: 'UserToken' },
    {
      kind: 'add_table_field',
      table: 'UserToken',
      fieldName: 'id',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserToken',
      fieldName: 'userUsername',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserToken',
      fieldName: 'name',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserToken',
      fieldName: 'token',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserToken',
      fieldName: 'expiresAt',
      type: 'date',
      required: false,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserToken',
      fieldName: 'createdAt',
      type: 'date',
      required: true,
      defaultValue: undefined,
    },
    { kind: 'add_table_primary_key', table: 'UserToken', fieldNames: ['token'] },
    { kind: 'add_table', table: 'UserPoolUser' },
    {
      kind: 'add_table_field',
      table: 'UserPoolUser',
      fieldName: 'userUsername',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    {
      kind: 'add_table_field',
      table: 'UserPoolUser',
      fieldName: 'userPoolId',
      type: 'string',
      required: true,
      defaultValue: undefined,
    },
    { kind: 'add_table_primary_key', table: 'UserPoolUser', fieldNames: ['userPoolId', 'userUsername'] },
    {
      kind: 'add_table_foreign_key',
      table: 'User',
      name: 'userPool',
      fieldNames: ['userPoolId'],
      foreignFieldNames: ['id'],
      foreignTable: 'UserPool',
      required: true,
    },
    {
      kind: 'add_table_foreign_key',
      table: 'Role',
      name: 'userPool',
      fieldNames: ['userPoolId'],
      foreignFieldNames: ['id'],
      foreignTable: 'UserPool',
      required: true,
    },
    {
      kind: 'add_table_foreign_key',
      table: 'UserRole',
      name: 'user',
      fieldNames: ['userUsername'],
      foreignFieldNames: ['username'],
      foreignTable: 'User',
      required: true,
    },
    {
      kind: 'add_table_foreign_key',
      table: 'UserRole',
      name: 'role',
      fieldNames: ['roleName', 'roleUserPoolId'],
      foreignFieldNames: ['name', 'userPoolId'],
      foreignTable: 'Role',
      required: true,
    },
    {
      kind: 'add_table_foreign_key',
      table: 'UserReset',
      name: 'user',
      fieldNames: ['userUsername'],
      foreignFieldNames: ['username'],
      foreignTable: 'User',
      required: true,
    },
    {
      kind: 'add_table_foreign_key',
      table: 'UserEmailVerify',
      name: 'user',
      fieldNames: ['userUsername'],
      foreignFieldNames: ['username'],
      foreignTable: 'User',
      required: true,
    },
    {
      kind: 'add_table_foreign_key',
      table: 'UserPoolCors',
      name: 'userPool',
      fieldNames: ['userPoolId'],
      foreignFieldNames: ['id'],
      foreignTable: 'UserPool',
      required: true,
    },
    {
      kind: 'add_table_foreign_key',
      table: 'UserRefreshToken',
      name: 'user',
      fieldNames: ['userUsername'],
      foreignFieldNames: ['username'],
      foreignTable: 'User',
      required: true,
    },
    {
      kind: 'add_table_foreign_key',
      table: 'UserRefreshToken',
      name: 'userPool',
      fieldNames: ['userPoolId'],
      foreignFieldNames: ['id'],
      foreignTable: 'UserPool',
      required: true,
    },
    {
      kind: 'add_table_foreign_key',
      table: 'UserToken',
      name: 'user',
      fieldNames: ['userUsername'],
      foreignFieldNames: ['username'],
      foreignTable: 'User',
      required: true,
    },
    {
      kind: 'add_table_foreign_key',
      table: 'UserPoolUser',
      name: 'user',
      fieldNames: ['userUsername'],
      foreignFieldNames: ['username'],
      foreignTable: 'User',
      required: true,
    },
    {
      kind: 'add_table_foreign_key',
      table: 'UserPoolUser',
      name: 'userPool',
      fieldNames: ['userPoolId'],
      foreignFieldNames: ['id'],
      foreignTable: 'UserPool',
      required: true,
    },
  ],
};
