tasks:
  install:
    image: node:16-alpine
    cmds:
      - npm install
    generates:
      - node_modules
    src:
      - package.json
      - package-lock.json

  build:
    image: node:16-alpine
    deps: [install, daita:install, common:build, relational:build]
    cmds:
      - npm run build
    src:
      - package.json
      - tsconfig.json
      - src
    generates:
      - dist

references:
  daita: ../../../build.yaml
  common: ../common/build.yaml
  relational: ../relational/build.yaml
