import { CreateIndexFormatter } from '../formatters/create-index-formatter';
import { DropIndexFormatter } from '../formatters/drop-index-formatter';
import { NowFormatter } from '../formatters/now';
import { NotifyFormatter } from '../formatters/notify-formatter';
import { ListenFormatter } from '../formatters/listen-formatter';
import { FieldFormatter } from '../../relational/sql/keyword/field/field-formatter';
import { NotEqualFormatter } from '../../relational/sql/operands/comparison/not-equal/not-equal-formatter';
import {
  AlterTableAddColumnFormatter,
  AlterTableAddForeignKeyFormatter,
  AlterTableDropColumnFormatter,
  AlterTableDropConstraintFormatter,
} from '../../relational/sql/ddl/alter-table/alter-table';
import { ConcatFormatter } from '../../relational/sql/function/string/concat/concat-formatter';
import { SubSelectFormatter } from '../../relational/sql/dml/select/subquery/sub-select-formatter';
import { Formatter } from '../../relational/formatter/formatter';
import { AvgFormatter } from '../../relational/sql/function/aggregation/avg/avg-formatter';
import { CreateTableFormatter } from '../../relational/sql/ddl/create-table/create-table-formatter';
import { EqualFormatter } from '../../relational/sql/operands/comparison/equal/equal-formatter';
import { GreaterThanFormatter } from '../../relational/sql/operands/comparison/greater-than/greater-than-formatter';
import { UpdateFormatter } from '../../relational/sql/dml/update/update-formatter';
import { SumFormatter } from '../../relational/sql/function/aggregation/sum/sum-formatter';
import { JoinFormatter } from '../../relational/sql/dml/select/join/join-formatter';
import { MinFormatter } from '../../relational/sql/function/aggregation/min/min-formatter';
import { DeleteFormatter } from '../../relational/sql/dml/delete/delete-formatter';
import { CreateSchemaFormatter } from '../../relational/sql/ddl/create-schema/create-schema';
import { MaxFormatter } from '../../relational/sql/function/aggregation/max/max-formatter';
import { LowerEqualThanFormatter } from '../../relational/sql/operands/comparison/lower-equal-than/lower-equal-than-formatter';
import { CreateViewFormatter } from '../../relational/sql/ddl/create-view/create-view';
import { GreaterEqualThanFormatter } from '../../relational/sql/operands/comparison/greater-equal-than/greater-equal-than-formatter';
import { BetweenFormatter } from '../../relational/sql/operands/comparison/between/between-formatter';
import { CountFormatter } from '../../relational/sql/function/aggregation/count/count-formatter';
import { ExistsFormatter } from '../../relational/sql/dml/select/subquery/exists-formatter';
import { LockTableFormatter } from '../../relational/sql/ddl/lock-table/lock-table';
import { NotInFormatter } from '../../relational/sql/operands/comparison/not-in/not-in-formatter';
import { OrderByFormatter } from '../../relational/sql/dml/select/order-by/order-by-formatter';
import { SelectFormatter } from '../../relational/sql/dml/select/select-formatter';
import { IsNullFormatter } from '../../relational/sql/operands/comparison/is-null/is-null-formatter';
import { InsertFormatter } from '../../relational/sql/dml/insert/insert-formatter';
import { LikeFormatter } from '../../relational/sql/operands/comparison/like/like-formatter';
import { LowerThanFormatter } from '../../relational/sql/operands/comparison/lower-than/lower-than-formatter';
import { AndFormatter } from '../../relational/sql/keyword/and/and-formatter';
import { TableFormatter } from '../../relational/sql/keyword/table/table-formatter';
import { OrFormatter } from '../../relational/sql/keyword/or/or-formatter';
import { NotBetweenFormatter } from '../../relational/sql/operands/comparison/not-between/not-between-formatter';
import { AllFormatter } from '../../relational/sql/keyword/all/all-formatter';
import { InFormatter } from '../../relational/sql/operands/comparison/in/in-formatter';
import { DropTableFormatter } from '../../relational/sql/ddl/drop-table/drop-table';
import { ValueFormatter } from '../../relational/sql/operands/value-formatter';
import { DropViewFormatter } from '../../relational/sql/ddl/drop-view/drop-view';
import { AliasFormatter } from '../../relational/sql/keyword/alias/alias-formatter';

export const postgresFormatter = new Formatter();
postgresFormatter.add(new AllFormatter());
postgresFormatter.add(new UpdateFormatter());
postgresFormatter.add(new NotEqualFormatter());
postgresFormatter.add(new MaxFormatter());
postgresFormatter.add(new SelectFormatter());
postgresFormatter.add(new SubSelectFormatter());
postgresFormatter.add(new ValueFormatter());
postgresFormatter.add(new SumFormatter());
postgresFormatter.add(new TableFormatter());
postgresFormatter.add(new NotInFormatter());
postgresFormatter.add(new JoinFormatter());
postgresFormatter.add(new AvgFormatter());
postgresFormatter.add(new MinFormatter());
postgresFormatter.add(new IsNullFormatter());
postgresFormatter.add(new FieldFormatter());
postgresFormatter.add(new BetweenFormatter());
postgresFormatter.add(new CountFormatter());
postgresFormatter.add(new OrderByFormatter());
postgresFormatter.add(new EqualFormatter());
postgresFormatter.add(new OrFormatter());
postgresFormatter.add(new AndFormatter());
postgresFormatter.add(new InFormatter());
postgresFormatter.add(new GreaterThanFormatter());
postgresFormatter.add(new GreaterEqualThanFormatter());
postgresFormatter.add(new CreateViewFormatter());
postgresFormatter.add(new DropViewFormatter());
postgresFormatter.add(new LowerThanFormatter());
postgresFormatter.add(new LowerEqualThanFormatter());
postgresFormatter.add(new NowFormatter());
postgresFormatter.add(new ExistsFormatter());
postgresFormatter.add(new AliasFormatter());
postgresFormatter.add(new NotBetweenFormatter());
postgresFormatter.add(new DeleteFormatter());
postgresFormatter.add(new LikeFormatter());
postgresFormatter.add(new ConcatFormatter());
postgresFormatter.add(new LockTableFormatter());
postgresFormatter.add(new DropTableFormatter());
postgresFormatter.add(new InsertFormatter());
postgresFormatter.add(new CreateSchemaFormatter());
postgresFormatter.add(new CreateTableFormatter());
postgresFormatter.add(new AlterTableAddColumnFormatter());
postgresFormatter.add(new AlterTableAddForeignKeyFormatter());
postgresFormatter.add(new AlterTableDropColumnFormatter());
postgresFormatter.add(new AlterTableDropConstraintFormatter());
postgresFormatter.add(new CreateIndexFormatter());
postgresFormatter.add(new DropIndexFormatter());
postgresFormatter.add(new NotifyFormatter());
postgresFormatter.add(new ListenFormatter());
