import { AlterTableAddColumnFormatter } from '../../relational/sql/ddl/alter-table/alter-table';
import { Formatter } from '../../relational/formatter/formatter';
import { CreateTableFormatter } from '../../relational/sql/ddl/create-table/create-table-formatter';
import { DropTableFormatter } from '../../relational/sql/ddl/drop-table/drop-table';
import { NowFormatter } from '../sql/function/date/now-formatter';
import { SqliteTableFormatter } from './sqlite-table-formatter';
import { ConcatPipeFormatter } from '../../relational/sql/function/string/concat/concat-pipe-formatter';
import { ansiFormatter } from '../../relational/formatter/ansi-formatter';
import { LeastFormatter } from '../../relational/sql/function/conditional/least/least-formatter';
import { GreatestFormatter } from '../../relational/sql/function/conditional/greatest/greatest-formatter';

export const sqliteFormatter = new Formatter();
sqliteFormatter.extend(ansiFormatter);
sqliteFormatter.add(new NowFormatter());
sqliteFormatter.add(new DropTableFormatter());
sqliteFormatter.add(new CreateTableFormatter());
sqliteFormatter.add(new AlterTableAddColumnFormatter());
sqliteFormatter.add(new SqliteTableFormatter());
sqliteFormatter.add(new ConcatPipeFormatter());
sqliteFormatter.add(new LeastFormatter());
sqliteFormatter.add(new GreatestFormatter());
