import { NowFormatter } from '../sql/function/date/now-formatter';
import { FieldFormatter } from '../../relational/sql/keyword/field/field-formatter';
import { NotEqualFormatter } from '../../relational/sql/operands/comparison/not-equal/not-equal-formatter';
import { AlterTableAddColumnFormatter } from '../../relational/sql/ddl/alter-table/alter-table';
import { ConcatFormatter } from '../../relational/sql/function/string/concat-formatter';
import { SubSelectFormatter } from '../../relational/sql/dml/select/subquery/sub-select-formatter';
import { Formatter } from '../../relational/formatter/formatter';
import { AvgFormatter } from '../../relational/sql/function/aggregation/avg-formatter';
import { CreateTableFormatter } from '../../relational/sql/ddl/create-table/create-table-formatter';
import { EqualFormatter } from '../../relational/sql/operands/comparison/equal/equal-formatter';
import { GreaterThanFormatter } from '../../relational/sql/operands/comparison/greater-than/greater-than-formatter';
import { UpdateFormatter } from '../../relational/sql/dml/update/update-formatter';
import { SumFormatter } from '../../relational/sql/function/aggregation/sum-formatter';
import { JoinFormatter } from '../../relational/sql/dml/select/join/join-formatter';
import { MinFormatter } from '../../relational/sql/function/aggregation/min-formatter';
import { DeleteFormatter } from '../../relational/sql/dml/delete/delete-formatter';
import { CreateSchemaFormatter } from '../../relational/sql/ddl/create-schema/create-schema';
import { MaxFormatter } from '../../relational/sql/function/aggregation/max-formatter';
import { LowerEqualThanFormatter } from '../../relational/sql/operands/comparison/lower-equal-than/lower-equal-than-formatter';
import { GreaterEqualThanFormatter } from '../../relational/sql/operands/comparison/greater-equal-than/greater-equal-than-formatter';
import { BetweenFormatter } from '../../relational/sql/operands/comparison/between/between-formatter';
import { CountFormatter } from '../../relational/sql/function/aggregation/count-formatter';
import { ExistsFormatter } from '../../relational/sql/dml/select/subquery/exists-formatter';
import { LockTableFormatter } from '../../relational/sql/ddl/lock-table/lock-table';
import { NotInFormatter } from '../../relational/sql/operands/comparison/not-in/not-in-formatter';
import { OrderByFormatter } from '../../relational/sql/dml/select/order-by/order-by-formatter';
import { SelectFormatter } from '../../relational/sql/dml/select/select-formatter';
import { IsNullFormatter } from '../../relational/sql/operands/comparison/is-null/is-null-formatter';
import { InsertFormatter } from '../../relational/sql/dml/insert/insert-formatter';
import { LikeFormatter } from '../../relational/sql/operands/comparison/like/like-formatter';
import { LowerThanFormatter } from '../../relational/sql/operands/comparison/lower-than/lower-than-formatter';
import { AndFormatter } from '../../relational/sql/keyword/and/and-formatter';
import { TableFormatter } from '../../relational/sql/keyword/table/table-formatter';
import { OrFormatter } from '../../relational/sql/keyword/or/or-formatter';
import { NotBetweenFormatter } from '../../relational/sql/operands/comparison/not-between/not-between-formatter';
import { AllFormatter } from '../../relational/sql/keyword/all/all-formatter';
import { InFormatter } from '../../relational/sql/operands/comparison/in/in-formatter';
import { DropTableFormatter } from '../../relational/sql/ddl/drop-table/drop-table';
import { ValueFormatter } from '../../relational/sql/operands/value-formatter';
import { AliasFormatter } from '../../relational/sql/keyword/alias/alias-formatter';

export const sqliteFormatter = new Formatter();
sqliteFormatter.add(new SelectFormatter());
sqliteFormatter.add(new UpdateFormatter());
sqliteFormatter.add(new SubSelectFormatter());
sqliteFormatter.add(new ValueFormatter());
sqliteFormatter.add(new MaxFormatter());
sqliteFormatter.add(new NotBetweenFormatter());
sqliteFormatter.add(new AllFormatter());
sqliteFormatter.add(new AvgFormatter());
sqliteFormatter.add(new TableFormatter());
sqliteFormatter.add(new NotInFormatter());
sqliteFormatter.add(new SumFormatter());
sqliteFormatter.add(new JoinFormatter());
sqliteFormatter.add(new MinFormatter());
sqliteFormatter.add(new InFormatter());
sqliteFormatter.add(new LikeFormatter());
sqliteFormatter.add(new IsNullFormatter());
sqliteFormatter.add(new FieldFormatter());
sqliteFormatter.add(new NotEqualFormatter());
sqliteFormatter.add(new CountFormatter());
sqliteFormatter.add(new OrderByFormatter());
sqliteFormatter.add(new EqualFormatter());
sqliteFormatter.add(new OrFormatter());
sqliteFormatter.add(new AndFormatter());
sqliteFormatter.add(new NowFormatter());
sqliteFormatter.add(new ExistsFormatter());
sqliteFormatter.add(new BetweenFormatter());
sqliteFormatter.add(new ConcatFormatter());
sqliteFormatter.add(new GreaterThanFormatter());
sqliteFormatter.add(new GreaterEqualThanFormatter());
sqliteFormatter.add(new LowerThanFormatter());
sqliteFormatter.add(new LowerEqualThanFormatter());
sqliteFormatter.add(new AliasFormatter());
sqliteFormatter.add(new DeleteFormatter());
sqliteFormatter.add(new LockTableFormatter());
sqliteFormatter.add(new DropTableFormatter());
sqliteFormatter.add(new InsertFormatter());
sqliteFormatter.add(new CreateSchemaFormatter());
sqliteFormatter.add(new CreateTableFormatter());
sqliteFormatter.add(new AlterTableAddColumnFormatter());
