tasks:
  install:
    image: node:16-alpine
    cmds:
      - npm install
    generates:
      - node_modules
    src:
      - package.json
      - package-lock.json

  build:
    image: node:16-alpine
    deps:
    - install
    - daita:install
    - node:build
    - common:build
    - orm:build
    - relational:build
    - auth-server:build
    - pg-adapter:build
    - mariadb-adapter:build
    - sqlite-adapter:build
    cmds:
      - npm run build
    src:
      - package.json
      - tsconfig.json
      - src
    generates:
      - dist

  package:
    deps: [build]
    cmds:
      - docker build @daita/auth -f Dockerfile ../../..

references:
  daita: ../../../build.yaml
  common: ../../packages/common/build.yaml
  orm: ../../packages/orm/build.yaml
  relational: ../../packages/relational/build.yaml
  node: ../../packages/node/build.yaml
  auth-server: ../../packages/auth-server/build.yaml
  pg-adapter: ../../packages/pg-adapter/build.yaml
  mariadb-adapter: ../../packages/mariadb-adapter/build.yaml
  sqlite-adapter: ../../packages/sqlite-adapter/build.yaml
