name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker:
    name: Build docker containers
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t @daita/auth -f src/containers/auth/Dockerfile .
        name: Build auth container
      - run: docker build -t @daita/http -f src/containers/http/Dockerfile .
        name: Build http container

  build:
    name: Build daita
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: lerna bootstrap
      - run: npm run build
