name: common
on: [push]

defaults:
  run:
    working-directory: packages/common
    
jobs:
  build_common:
    name: Build common
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build
