name: publish
on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish daita
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npx lerna bootstrap
      - run: npm run build
        working-directory: packages/internal/npm-publish
      - run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
